name: test
on: [push, pull_request]
jobs:
  test:
    name: Build and run it
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]
        python: [3.14]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: |
          ulimit -s
          echo "==="
          ulimit -s 4096
          ulimit -s
          echo "==="
          cc a.c
          ./a.out
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          PRERELEASE_FLAG=""
          if [[ "${{ github.ref_name }}" =~ [ab][0-9] ]]
          then
            PRERELEASE_FLAG="--prerelease"
          fi
          echo ${PRERELEASE_FLAG}
        if: startsWith(github.ref, 'refs/tags/')
